// Generated by CoffeeScript 2.7.0

// This is Titanium to JavaScript transpiller - codename Athena
// It was written by André Pereira (AndrewNation) for converting
// Titanium code to JavaScript. It's the script used in Gusleothew
// playground and the Andrew Toolchain interpreter.
var JavaScriptOutput, code, convertTitanium_To_JS, javascript, parseConstants, parsePrint, parseTitaniumLine, parseTitaniumToJavaScript, parseVariables, rules, titanium;

JavaScriptOutput = [];

code = [];

rules = {
  constantDeclaration: /DEF .*[A-Za-z_] = "?.*[A-Za-z0-9\(\)]?"?/,
  printCommand: /print\("?.*[\[\]0-9A-Z a-z!,_ ?:><=!]?"?\)/g,
  variableDeclaration: /DECL .*[A-Za-z_] = "?.*[A-Za-z0-9\+]?"?/gm
};

titanium = {
  constKeyword: "DEF",
  printKeyword: "print(",
  varKeyword: "DECL"
};

javascript = {
  constKeyword: "const",
  printKeyword: "console.log(",
  varKeyword: "let"
};

parseVariables = function (statement) {
  return statement.replace(titanium.varKeyword, javascript.varKeyword);
};

parsePrint = function (statement) {
  return statement.replace(titanium.printKeyword, javascript.printKeyword);
};

parseConstants = function (statement) {
  return statement.replace(titanium.constKeyword, javascript.constKeyword);
};

parseTitaniumLine = function (line) {
  if (line.match(rules.constantDeclaration)) {
    return parseConstants(line);
  }
  if (line.match(rules.variableDeclaration)) {
    return parseVariables(line);
  }
  if (line.match(rules.printCommand)) {
    return parsePrint(line);
  }
};


//window.alert "[error] issues have been found in your Titanium code. Please verify it with Titanium CLI or Gusleothew playground"
parseTitaniumToJavaScript = function (code) {
  var i, len, line, results;
  results = [];
  for (i = 0, len = code.length; i < len; i++) {
    line = code[i];
    results.push(JavaScriptOutput.push(parseTitaniumLine(line)));
  }
  return results;
};

convertTitanium_To_JS = function (code) {
  var JSoutput, code_line, i, len, output;
  JavaScriptOutput = [];
  parseTitaniumToJavaScript(code);
  JSoutput = "";
  for (i = 0, len = JavaScriptOutput.length; i < len; i++) {
    code_line = JavaScriptOutput[i];
    if (code_line !== void 0) {
      JSoutput += code_line + "\n";
    }
  }
  var header = "//ProjectAthena, Titanium to JS code converter. \n//Created by AndrewNation\n\n"
  output = window.open("", "ProjectAthena - by AndrewNation", "toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=780,height=200,top=" + (screen.height - 400) + ",left=" + (screen.width - 840));
  output.document.body.innerHTML = "<strong><pre>" + header + JSoutput + "</pre></strong>";
  output.document.body.style['backgroundColor'] = "#000";
  output.document.body.style['color'] = "#fff";
};

